/// Declares a typed route table and generates the public API for working with it.
///
/// Apply this macro to a type that contains `@Route`, `@Layout`, `@NotFound`, and `@RouteError`
/// declarations. The macro generates:
///
/// - `RouteView`: the typed view union rendered by this route set
/// - `RouteSet`: the compiled route tree plus route handles
/// - `Handles`: strongly typed route handles for each declared route
/// - `Provider`: a route-set-specific environment provider for generated links
/// - `Link`: a route-set-specific navigation view
/// - `routes()`: builds the generated route set
/// - `router()`: creates either `Router<RouteView>` or `HashRouter<RouteView>`
///
/// `mode` selects whether generated links and routers use browser path routing or hash routing.
@attached(
  member,
  names: named(RouteView),
  named(RouteSet),
  named(_routerEnvironmentKey),
  named(Handles),
  named(Provider),
  named(Link),
  named(routes),
  named(router)
)
public macro Routes(mode: RoutesMode = .path) =
  #externalMacro(module: "ElementaryRouterMacros", type: "RoutesMacro")

/// Selects the router mode generated by `@Routes`.
public enum RoutesMode {
  /// Uses normal browser paths such as `/users/42`.
  case path
  /// Uses fragment-based URLs such as `/#/users/42`.
  case hash
}

/// Declares a leaf route on a member inside a `@Routes` type.
///
/// The annotated declaration becomes part of the generated route tree. Path parameters are read
/// from the route path, query parameters are declared with `Query`, and wildcard segments are
/// declared with `Wildcard`.
@attached(peer, names: arbitrary)
public macro Route(_ path: String) =
  #externalMacro(module: "ElementaryRouterMacros", type: "RouteMacro")

/// Declares a layout route on a member inside a `@Routes` type.
///
/// Layouts participate in the route match stack and are rendered from parent to child. Use
/// `Outlet` inside the layout body to place the child route content.
@attached(peer, names: arbitrary)
public macro Layout(_ path: String) =
  #externalMacro(module: "ElementaryRouterMacros", type: "LayoutMacro")

/// Declares the renderer used when no route matches the current location.
@attached(peer, names: arbitrary)
public macro NotFound() = #externalMacro(module: "ElementaryRouterMacros", type: "NotFoundMacro")

/// Declares the renderer used when a matched route throws `RouteValueError` while rendering.
@attached(peer, names: arbitrary)
public macro RouteError() =
  #externalMacro(module: "ElementaryRouterMacros", type: "RouteErrorMacro")
